version: "3"
services:
    apache:
        volumes:
            - ./:/var/www/html
        build: .
        ports:
            - 8090:80
    composer:
        image: composer/composer:php7
        command: install
        volumes:
          - ./:/app